### ISSUE TITLE
[DOC] 建议wiki中的 #安装sdcc 新增【二进制安装】子章节

### ISSUE THREAD

**Issue by WeilunFong** [IOsetting/HML_FwLib_STC12#1]
若用户不选择使用流行的apt-get或yum命令安装，无非为如下两点原因：
* 编译环境无法直接联网；
* 可用的软件源中没有期望版本的软件包。

编译安装方式对于大部分用户来说并不友好，因为：
* 环境甚至没有预装HOSTCC，例如gcc、clang等；
* 构建过程中可能存在依赖缺失的问题，sdcc编译器本身即依赖boost c++；
* 编译命令有时需根据自身环境与需要进行调整才能正常构建；
* 卸载、更新与多版本共存的操作较为麻烦；

此时，若采用二进制方式，仅需将与运行环境相匹配的软件包解压至一个合适的路径下（通常为`/opt`），加以少量的环境变量配置即可运行软件；此外，由于软件的安装路径取决于解压路径，因此可以很轻松地通过修改环境变量`PATH`以切换不同版本的编译器，这也是`usr/env.sh`文件编写的初衷，其内容形式参考了[yocto](https://www.yoctoproject.org/)工程模板。多版本sdcc共存安装参考路径如下：
```
/opt
 + --- sdcc
        + --- sdcc-4.1.0
        + --- sdcc-3.6.0
```

sdcc官方提供了主流的amd64平台的二进制安装包，参见[Small Device C Compiler -  Browse /sdcc-linux-amd64 at SourceForge.net](https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/)，将其中的压缩包解压并添加bin目录至环境变量`PATH`中即可运行。

望采纳！

**Comment by IOsetting** [comment]
多谢提醒, 这个方式不错, 已更新至文档.
